on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  compile:
    name: "Compile Arduino Sketches"
    uses: arduino/compile-sketches/action.yml@v1.1.2
    with:
      fqbn: "arduino:avr:pro"
      sketch-paths: src
      libraries: |
        - name: Arduino
        - name: EEPROM
        - name: VescUart
