on:
  push:
    branches:
    - main
  pull_request:
    types: [ 'opened', 'reopened', 'synchronize']
jobs:
  build:
    name: compile for pro mini
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile for pro mini
        uses: arduino/compile-sketches@v1
        with: &defaultBuildOpts
          verbose: true
          libraries: |
            - source-url: https://github.com/SolidGeek/VescUart.git
          cli-compile-flags: |
            - --library="${{ github.workspace }}"
          fqbn: "arduino:avr:pro"
          enable-deltas-report: false
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
          sketch-paths: |
            - UartBrakes

      - name: Compile for itsy bitsy 3v
        uses: arduino/compile-sketches@v1
        with:
          <<: *defaultBuildOpts
          fqbn: "adafruit:avr:itsybitsy32u4_3V"
