on:
  push:
    branches:
    - main
  pull_request:
    types: [ 'opened', 'reopened', 'synchronize']
jobs:
  build:
    name: compile for pro mini
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile all examples
        uses: arduino/compile-sketches@v1
        with:
          libraries: |
            - source-url: https://github.com/SolidGeek/VescUart.git
          cli-compile-flags: --libraries src
          fqbn: "arduino:avr:pro"
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
          sketch-paths: |
            - UartBrakes
