on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  - name: "Compile Arduino Sketches"
    uses: arduino/compile-sketches@v1
    with:
      fqbn: "arduino:avr:pro"
      sketch-paths:
        - src
      libraries: |
        - name: Arduino
        - name: EEPROM
        - name: VescUart